# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpurl" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "d32a477874fdb36a3a9d2c4cd4de1f3ac44138460f36714282ce439c5fa09b9a"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd0d7dbfbcc9a4b4f66e60332e2b049641ce3138a547066c3d2be9cd5996cce2"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0b80a63eec005faa5b7a5fb6d1d0e1692172d8df220d8f58ef476e9ca6deccb3"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "72ba91a468e6a9150335074ee2fa435524a7d0351f94d41a23edc51fbcdb0e89"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcpurl"
  desc "stdio to Streamable HTTP MCP bridge with local OAuth 2.1 PKCE"
  homepage "https://github.com/vmkteam/mcpurl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpurl"

  # No zap stanza required
end
