# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpurl" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "8d860abd75659acba9f04ae20dc036259d7620de535b46ab51e7f3a6bbd227d9"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "12b647f2ae6f45e8b9994de50f706dcffaaf2f2efe899ad417aba4a7a87a2d5b"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "499be768ea6eadd8522eba77949b85eea89c9fc491b86aec8ec7adeb507c8c55"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc9d54f1d4df612c9da4619442d0b65b89558d7f22e35222b308f84aa158be9b"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mcpurl"
  desc "stdio to Streamable HTTP MCP bridge with local OAuth 2.1 PKCE"
  homepage "https://github.com/vmkteam/mcpurl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpurl"

  # No zap stanza required

end
