# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpurl" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "0bec2e81a738931957a516e40989f70e1ebd51be45a6c5857137f16175d12a36"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f04e8eb977876c66ed759bf1cb6b1e51cea48c1213f047e2f1f67a0bc9f15e3"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f299be3c33e3d3597d5e5e28bb229641fa08b8c8b07b88c70dd28f0e2b568702"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "159675e0d6c809c22778c12dbd818c24ecdd538479b228028eb2e856e73ce60d"
      url "https://github.com/vmkteam/mcpurl/releases/download/v#{version}/mcpurl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mcpurl"
  desc "stdio to Streamable HTTP MCP bridge with local OAuth 2.1 PKCE"
  homepage "https://github.com/vmkteam/mcpurl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpurl"

  # No zap stanza required

end
