# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcurl" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "3726845f552d70f4e4981011077b6cb022c3b580df4a9da20161fec500a74fec"
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b5c521c0778d84aab3e6daf8e071bc37df3c2a9aee5148523dcdae3a7379af3b"
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88b10b5d9fa86e481bfff94bd195a83d8cbe385a1b07807d0c4e56a64360ab8f"
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a078d1fff19778eb49dff81fe2c724a506ae524780880e5f45e1cd33e288965b"
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pcurl"
  desc "Private curl — hide auth headers from AI agents"
  homepage "https://github.com/vmkteam/pcurl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcurl"

  # No zap stanza required

end
