# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcurl" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_darwin_amd64.tar.gz"
      sha256 "311ed6f968167a5c5147c33355f9adbf8d29cb5f83238f9e5f20a3d34ac0ec9f"
    end
    on_arm do
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_darwin_arm64.tar.gz"
      sha256 "63a5a07bf3043cda2980418862db1da0d4d5595008ae25edb27183122c47c658"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_linux_amd64.tar.gz"
      sha256 "bc053135af489798774e601251880e7787bdfa93df43e37486611257a2157567"
    end
    on_arm do
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_linux_arm64.tar.gz"
      sha256 "abea28f84c6301ca27ea19ff9090b6a3a75729602899aad8596508161156d2d5"
    end
  end

  name "pcurl"
  desc "Private curl — hide auth headers from AI agents"
  homepage "https://github.com/vmkteam/pcurl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcurl"

  # No zap stanza required

end
