# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcurl" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_darwin_amd64.tar.gz"
      sha256 "ddb3924c37e0deffb7c176d83397fcb0098ff89129f2bb3e881ce0f7d6909c40"
    end
    on_arm do
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_darwin_arm64.tar.gz"
      sha256 "3a0a908966692fc39f88eef14fc0465185458a5917b4d311f693928ecea88ca1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_linux_amd64.tar.gz"
      sha256 "ea8230d779b775a90d761eeaf516f67fe04640546b970796ff510df718334db3"
    end
    on_arm do
      url "https://github.com/vmkteam/pcurl/releases/download/v#{version}/pcurl_#{version}_linux_arm64.tar.gz"
      sha256 "f4a9b919e75638579181de14b53f4cc05580e2a0d81f33c523dce20bc5a60636"
    end
  end

  name "pcurl"
  desc "Private curl — hide auth headers from AI agents"
  homepage "https://github.com/vmkteam/pcurl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcurl"

  # No zap stanza required

end
