# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgmigrator" do
  name "pgmigrator"
  desc "Command-line tool for PostgreSQL migrations"
  homepage "https://github.com/vmkteam/pgmigrator"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgmigrator"

  on_macos do
    on_intel do
      url "https://github.com/vmkteam/pgmigrator/releases/download/v#{version}/pgmigrator_#{version}_darwin_amd64.tar.gz"
      sha256 "eaf90dcf3656f5605b16d5ee008ba782334dbcef975cfc7f3483823c4b1b689a"
    end
    on_arm do
      url "https://github.com/vmkteam/pgmigrator/releases/download/v#{version}/pgmigrator_#{version}_darwin_arm64.tar.gz"
      sha256 "8791f4c8382fc6c1426b3c0149704f98ed4d380de7d57f12e2e0069aea269a00"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vmkteam/pgmigrator/releases/download/v#{version}/pgmigrator_#{version}_linux_amd64.tar.gz"
      sha256 "d1da5414d24ca7b836695b851c39e77711a7235fd1d0992351a9187ea280ba7a"
    end
    on_arm do
      url "https://github.com/vmkteam/pgmigrator/releases/download/v#{version}/pgmigrator_#{version}_linux_arm64.tar.gz"
      sha256 "5bdec2698c4603ee6d1512c65b292b99d40333e4266b973c608aea46528e4505"
    end
  end

  # No zap stanza required
end
