# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgmigrator" do
  name "pgmigrator"
  desc "Command-line tool for PostgreSQL migrations"
  homepage "https://github.com/vmkteam/pgmigrator"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgmigrator"

  on_macos do
    on_intel do
      url "https://github.com/vmkteam/pgmigrator/releases/download/v#{version}/pgmigrator_#{version}_darwin_amd64.tar.gz"
      sha256 "7faf1a242d9018660206a82387c8793f81c6ab7d2ca2c1150855cf0e19f1ce39"
    end
    on_arm do
      url "https://github.com/vmkteam/pgmigrator/releases/download/v#{version}/pgmigrator_#{version}_darwin_arm64.tar.gz"
      sha256 "d229b1fabbfdee58a639e297ad2eb439388dacdbb81f4e90d792eca19e8ddd1c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vmkteam/pgmigrator/releases/download/v#{version}/pgmigrator_#{version}_linux_amd64.tar.gz"
      sha256 "c5ae2f7287e86e83a21a736b39b5c1ba0e5ae8fbd0e5f4290ea2a058c682509b"
    end
    on_arm do
      url "https://github.com/vmkteam/pgmigrator/releases/download/v#{version}/pgmigrator_#{version}_linux_arm64.tar.gz"
      sha256 "2da7fb7fb1b0519ec8f5f451d313953e2bb4b8e4c498fc0263e62da6aa61ba30"
    end
  end

  # No zap stanza required
end
