# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgdesigner < Formula
  desc "PostgreSQL schema designer — ERD, linting, diffing, sample data"
  homepage "https://pgdesigner.io"
  version "0.0.3"
  license "PolyForm-Noncommercial-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vmkteam/pgdesigner/releases/download/v0.0.3/pgdesigner-darwin-amd64.tar.gz"
      sha256 "83bac36a9d31ff401c1dd6f25d337e915bd59d28ab39127c703222c46ef676c5"

      define_method(:install) do
        bin.install "pgdesigner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vmkteam/pgdesigner/releases/download/v0.0.3/pgdesigner-darwin-arm64.tar.gz"
      sha256 "3ac24971d70c91fee9bb5e6cbdd62c1722b395dcd6cce4e1524be4281e7516a2"

      define_method(:install) do
        bin.install "pgdesigner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmkteam/pgdesigner/releases/download/v0.0.3/pgdesigner-linux-amd64.tar.gz"
      sha256 "e47a0bae1b25f638b99cf9104755426bd15adfc40a049ec395e25ddec4b54eab"
      define_method(:install) do
        bin.install "pgdesigner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmkteam/pgdesigner/releases/download/v0.0.3/pgdesigner-linux-arm64.tar.gz"
      sha256 "66189387d66525d2dc231ef1f21f14679ef8e911d3cb2dcc5449cc49d58bc234"
      define_method(:install) do
        bin.install "pgdesigner"
      end
    end
  end

  test do
    system "#{bin}/pgdesigner version"
  end
end
