# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgdesigner < Formula
  desc "PostgreSQL schema designer — ERD, linting, diffing, sample data"
  homepage "https://pgdesigner.io"
  version "0.0.5"
  license "PolyForm-Noncommercial-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vmkteam/pgdesigner/releases/download/v0.0.5/pgdesigner-darwin-amd64.tar.gz"
      sha256 "dce3192736a1c4dec56812d442eee9944afe85b61682b4928a92c6977d7025bb"

      define_method(:install) do
        bin.install "pgdesigner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vmkteam/pgdesigner/releases/download/v0.0.5/pgdesigner-darwin-arm64.tar.gz"
      sha256 "e80b0bc0cfc7f8083b30235ad02f486bebde182f889add67a7a53c850bc76af9"

      define_method(:install) do
        bin.install "pgdesigner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmkteam/pgdesigner/releases/download/v0.0.5/pgdesigner-linux-amd64.tar.gz"
      sha256 "6bcbe3ada6acb3300d2c42c619b935465efa8495aad9a0fd359d3bd9641f227a"
      define_method(:install) do
        bin.install "pgdesigner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmkteam/pgdesigner/releases/download/v0.0.5/pgdesigner-linux-arm64.tar.gz"
      sha256 "3e4d327706c2dda1c2ee144a9a63a3b8765a6147c486cf4802f60d051383f9fd"
      define_method(:install) do
        bin.install "pgdesigner"
      end
    end
  end

  test do
    system "#{bin}/pgdesigner version"
  end
end
